# 섹션 10. 비동기-동시성 프로그래밍 3

## async:await

async/await은 비동기 코드를 동기적으로 다룰 수 있게 함.

```javascript
function delay(target) {
  return new Promise((resolve) => setTimeout(() => resolve(target), 500));
}

// Promise가 보이지는 않지만, Promise를 return하는 함수에만 await을 적용할 수 있다.
async function func1() {
  const a = await delay(10);
  const b = await delay(5);

  console.log(a + b);
}
func1(); // 15

async function func2() {
  const a = await delay(10);
  const b = await delay(5);

  // Promise값을 다루지 않더라도, async함수는 무조건 Promise를 return.
  return a + b;
}
console.log(func2()); // Promise { <pending> }
func2().then(console.log); // 15
go(func2(), console.log); // 15
```

그러나 모든 상황을 동기처럼 다룰 수 있는 것은 아니다.

<br/>

## Array.prototype.map이 있는데 왜 FxJS의 map 함수가 필요한지?

Array.prototype의 메서드들은 지연성을 지원하지 않고, 동시성을 다룰 수 없다.

```javascript
function delay(target) {
  return new Promise((resolve) => setTimeout(() => resolve(target), 500));
}

async function func1() {
  const list = [1, 2, 3, 4];
  const tmp = list.map(async (target) => await delay(target * target));
  console.log(tmp);
  // [
  //   Promise { <pending> },
  //   Promise { <pending> },
  //   Promise { <pending> },
  //   Promise { <pending> }
  // ]

  const res = await tmp;
  console.log(res);
  // [
  //   Promise { <pending> },
  //   Promise { <pending> },
  //   Promise { <pending> },
  //   Promise { <pending> }
  // ]
}
func1();

async function func2() {
  const list = [1, 2, 3, 4];
  const tmp = map((target) => delay(target * target), list);
  console.log(tmp); // Promise { <pending> }

  const res = await tmp;
  console.log(res); // [1, 4, 9, 16]
}
func2();

async function func3() {
  const list = [1, 2, 3, 4];
  const res = await map((target) => delay(target * target), list);
  console.log(res); // [ 1, 4, 9, 16 ]
}
func3();
```

FxJS는 현재까지 진행한 강의들과 거의 동일한 코드들로 구성되어있는 라이브러리.<br/>
https://www.inflearn.com/questions/9501/fxjs를 참고.

<br/>

## 이제 비동기는 async:await로 제어할 수 있는데 왜 파이프라인이필요한지?

async:await이 해결하고자 하는 문제는 표현식으로 갇혀있는 Promise를 문장형으로 다루는 것.

파이프라이닝과 이터러블 중심 프로그래밍이 해결하고자 하는 문제는<br/>
명령형 프로그래밍을 하지않고 더 안전하게 함수 합성을 하고자 하는 것.

파이프라이닝 방식의 코딩에서 비동기를 동기적으로 다룰 수 있기 때문에 착각하고는 하는데,<br/>
둘은 비교 대상이 아니고, 다른 문제를 해결하기 위한 별개의 기술.

```javascript
// 파이프라이닝 프로그래밍
function func1() {
  return go(
    [1, 2, 3, 4, 5, 6, 7, 8],
    L.map((target) => delay(target * target)),
    L.filter((target) => delay(target % 2)),
    L.map((target) => delay(target + 1)),
    take(3),
    reduce((a, b) => delay(a + b))
  );
}
go(func1(), console.log); // 38

// async/await 프로그래밍 (위와 똑같이 동작하도록 기능적으로만 구현)
async function func2(list) {
  let tmp = [];
  for (const a of list) {
    const b = await delay(a * a);
    if (await delay(b % 2)) {
      const c = await delay(b + 1);
      tmp.push(c);
      if (tmp.length === 3) {
        break;
      }
    }
  }
  let res = tmp[0];
  let i = 0;
  while (++i < tmp.length) {
    res = await delay(res + tmp[i]);
  }
  return res;
}
go(func2([1, 2, 3, 4, 5, 6, 7, 8]), console.log); // 38
```

무슨 말인지 알겠는가?

<br/>

## async:await와 파이프라인을 같이 사용하기도 하는지?

다음처럼 사용할 수 있다.

```javascript
async function func(list) {
  const res1 = await go(
    list,
    L.map((target) => delay(target * target)),
    L.filter((target) => delay(target % 2)),
    L.map((target) => delay(target + 1)),
    take(3),
    reduce((a, b) => delay(a + b))
  );

  const res2 = await go(
    list,
    L.map((target) => delay(target * target)),
    L.filter((target) => delay(target % 2)),
    reduce((a, b) => delay(a + b))
  );

  return res1 + res2;
}
go(func([1, 2, 3, 4, 5, 6, 7, 8]), console.log); // 96
```

<br/>

## 동기 상황에서 에러 핸들링은 어떻게 해야하는지?

typescript를 사용하듯이 에러가 발생할 수 있는 상황에 대한 처리를 미리 하는게 최선<br/>
이지만? 보통 다음과같이 처리를 할 수 있다.

```javascript
function func(list) {
  try {
    return list
      .map((target) => target + 10)
      .filter((target) => target % 2)
      .slice(0, 2);
  } catch (err) {
    console.log(err);
    return [];
  }
}
```

<br/>

## 비동기 상황에서 에러 핸들링은 어떻게 해야하는지?

```javascript
async function func(list) {
  try {
    return await list
      .map(async (target) => {
        return await new Promise((resolve) => {
          resolve(JSON.parse(target));
        });
      })
      .filter((target) => target % 2)
      .slice(0, 2);
  } catch (err) {
    console.log(err); // 정상적으로 에러가 넘어오지 않음.
    return [];
  }
}
```

결론 : 파이프라이닝 프로그래밍이 아닌 상황에서의 비동기 에러핸들링은 생각보다 쉽지않다.<br/>
해결 방법은 후술한다.

<br/>

## 동기/비동기 에러 핸들링에서의 파이프라인의 이점은?

```javascript
async function func1(list) {
  try {
    return await go(
      list,
      map((target) => {
        return new Promise((resolve) => {
          resolve(JSON.parse(target));
        });
      }),
      filter((target) => target % 2),
      take(2)
    );
  } catch (err) {
    // 이 자리로 넘어오려면 try문 내에서 Promise.reject로 평가가 이루어져야 함.
    // 이곳에서 롤백처리등을 할 수 있다.
    console.log(err); // 정상적으로 에러가 넘어옴.
    return [];
  }
}
// 이자리에서 에러에 대한 후속처리를 이룬다.
// 다만 에러가 발생되면 []를 return하도록 처리해놨기 때문에, catch되지 않는다.
func1(["1", "2", "3", "4", "5", "{"])
  .then((target) => console.log(target))
  .catch((err) => console.log("error handling", err));

// 동기 함수의 경우도 마찬가지.
function func2(list) {
  try {
    return go(
      list,
      map((target) => JSON.parse(target)),
      filter((target) => target % 2),
      take(2)
    );
  } catch (err) {
    console.log(err); // 정상적으로 에러가 넘어옴.
    return [];
  }
}
func2(["1", "2", "3", "4", "5", "{"])
  .then((target) => console.log(target))
  .catch((err) => console.log("error handling", err));
```

<br/>

## 마무리하며

<생략>

<br/>
